# see: https://stack.jimmycai.com/config/menu

# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
# Priority of the item, lower value means higher priority.
weight = -999
[main.params]
icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/anemele"

[social.params]
icon = "brand-github"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"
